BibliometricsApp/app/v1/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

BibliometricsApp/app/v1/controllers/exporterController.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template,\
                  session, redirect, url_for,\
                  request, jsonify, make_response,\
                  current_app
from flask_babel import gettext, ngettext

import pyexcel as pe
import io
import time
import ast

VERSION = "v1"
mod_export = Blueprint('v1_exporterController', __name__, url_prefix='/'+VERSION)


def gfile_download(filename = 'export', extension = 'xlsx', book = {}):
    #generamos el excel
    book = pe.Book(book)
    io1 = io.BytesIO()
    book.save_to_memory(extension, io1)
    output = make_response(io1.getvalue())
    output.headers["Content-Disposition"] = "attachment; filename=%s.%s" %(filename, extension)
    output.headers["Content-type"] = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    return output


@mod_export.route('/export', methods = ['POST'])
def export():
    #Leemos Formulario y obtenemos filtros
    form =  request.form
    
    header1 = form.get('header1', 'Header1')
    header2 = form.get('header2', 'Header2')
    filters = ast.literal_eval(form.get('filters', '{}'))
    data = ast.literal_eval(form.get('data', '{}'))

    return simple_document_dict_export(data, filters, header1, header2)
    #return gfile_download("[SciELO]Empty", "xlsx", book)

@mod_export.route('/export_journal', methods = ['POST'])
def export_journal():
    #Leemos Formulario y obtenemos filtros
    form =  request.form
    
    header1 = form.get('header1', 'Header1')
    header2 = form.get('header2', 'Header2')
    filters = ast.literal_eval(form.get('filters', '{}'))
    data = ast.literal_eval(form.get('data', '{}'))

    return simple_journal_dict_export(data, filters, header1, header2)

def simple_journal_dict_export(data = {}, filters = {}, header1 = 'Header1', header2 = 'Header2'):
    book = {}
    dt = time.gmtime()
    data_sheet = "Data"
    book[data_sheet] = []
    book[data_sheet].append([gettext("Date"),
                             gettext("Time"),
                             gettext(header1),
                             gettext(header2),
                             gettext("# Documents"),
                             gettext("# Journals")
                            ])
    for key, values in list(data.items()):
        for k, v in list(values.items()):
            book[data_sheet].append([time.strftime("%d-%m-%Y", dt),
                                     time.strftime("%H:%M:%S", dt),
                                     key,
                                     k,
                                     v['documents'],
                                     v['journals']
                                    ])
    #Filters
    filters_sheet = "Filters"
    book[filters_sheet] = []
    if 'scope' in filters:
        book[filters_sheet].append(['Scope', filters['scope']])
    if 'tabulation' in filters:
        book[filters_sheet].append(['Tabulation', filters['tabulation']])
    if 'collections' in filters:
        for c in filters['collections']:
            book[filters_sheet].append(['Collection', c[1]])
    if 'journals_status' in filters:
        book[filters_sheet].append(['Journal Status', filters['journals_status']])
    if 'journals' in filters:
        for j in filters['journals']:
            book[filters_sheet].append(['Journal', j])
    if 'languages' in filters:
        for l in filters['languages']:
            book[filters_sheet].append(['Language', l[1]])
    if 'thematic_areas' in filters:
        for ta in filters['thematic_areas']:
            book[filters_sheet].append(['SciELO Thematic Area', ta])
    if 'wos_thematic_areas' in filters:
        for wta in filters['wos_thematic_areas']:
            book[filters_sheet].append(['WOS Thematic Area', wta])
    if 'document_type' in filters:
        book[filters_sheet].append(['Document Type', filters['document_type']])
    if 'document_type_details' in filters:
        for dtd in filters['document_type_details']:
            book[filters_sheet].append(['Document', dtd])
    return gfile_download("[SciELO]Journals", "xlsx", book)

def simple_document_dict_export(data = {}, filters = {}, header1 = 'Header1', header2 = 'Header2'):
    book = {}
    dt = time.gmtime()
    data_sheet = "Data"
    book[data_sheet] = []
    book[data_sheet].append(["","","","","",gettext("Documents by Language"),"","","","",gettext("Documents by Thematic Area"),"","","","","","","","","",gettext("Citable Documents Type"),"","","","","","","","","",""])
    book[data_sheet].append([gettext("Date"),
                             gettext("Time"),
                             gettext(header1),
                             gettext(header2),
                             gettext("# Documents"),
                             gettext("English"),
                             gettext("Spanish"),
                             gettext("Portuguese"),
                             gettext("Other"),
                             gettext("Total"),
                             gettext("Health Sciences"),
                             gettext("Human Sciences"),
                             gettext("Biological Sciences"),
                             gettext("Agricultural Sciences"),
                             gettext("Applied Social Sciences"),
                             gettext("Exact and Earth Sciences"),
                             gettext("Engineering"),
                             gettext("Linguistics, Letters and Arts"),
                             gettext("Undefined"),
                             gettext("Total"),
                             gettext("Research Article"),
                             gettext("Editorial"),
                             gettext("Book Review"),
                             gettext("Case Report"),
                             gettext("Review Article"),
                             gettext("Rapid Communication"),
                             gettext("Letter"),
                             gettext("Brief Report"),
                             gettext("Article Commentary"),
                             gettext("Abstract"),
                             gettext("Total")
                            ])
    for key, values in list(data.items()):
        for k, v in list(values.items()):
            book[data_sheet].append([time.strftime("%d-%m-%Y", dt),
                                     time.strftime("%H:%M:%S", dt),
                                     key,
                                     k,
                                     v['documents'],
                                     v['by_language']['en'],
                                     v['by_language']['es'],
                                     v['by_language']['pt'],
                                     v['by_language']['other'],
                                     v['by_language']['total'],
                                     v['by_thematic_area']["Health Sciences"],
                                     v['by_thematic_area']["Human Sciences"],
                                     v['by_thematic_area']["Biological Sciences"],
                                     v['by_thematic_area']["Agricultural Sciences"],
                                     v['by_thematic_area']["Applied Social Sciences"],
                                     v['by_thematic_area']["Exact and Earth Sciences"],
                                     v['by_thematic_area']["Engineering"],
                                     v['by_thematic_area']["Linguistics, Letters and Arts"],
                                     v['by_thematic_area']["undefined"],
                                     v['by_thematic_area']["total"],
                                     v['by_citable_doc']["research-article"],
                                     v['by_citable_doc']["editorial"],
                                     v['by_citable_doc']["book-review"],
                                     v['by_citable_doc']["case-report"],
                                     v['by_citable_doc']["review-article"],
                                     v['by_citable_doc']["rapid-communication"],
                                     v['by_citable_doc']["letter"],
                                     v['by_citable_doc']["brief-report"],
                                     v['by_citable_doc']["article-commentary"],
                                     v['by_citable_doc']["abstract"],
                                     v['by_citable_doc']["total"]
                                    ])
    #Filters
    filters_sheet = "Filters"
    book[filters_sheet] = []
    if 'scope' in filters:
        book[filters_sheet].append(['Scope', filters['scope']])
    if 'tabulation' in filters:
        book[filters_sheet].append(['Tabulation', filters['tabulation']])
    if 'collections' in filters:
        for c in filters['collections']:
            book[filters_sheet].append(['Collection', c[1]])
    if 'journals_status' in filters:
        book[filters_sheet].append(['Journal Status', filters['journals_status']])
    if 'journals' in filters:
        for j in filters['journals']:
            book[filters_sheet].append(['Journal', j])
    if 'languages' in filters:
        for l in filters['languages']:
            book[filters_sheet].append(['Language', l[1]])
    if 'thematic_areas' in filters:
        for ta in filters['thematic_areas']:
            book[filters_sheet].append(['SciELO Thematic Area', ta])
    if 'wos_thematic_areas' in filters:
        for wta in filters['wos_thematic_areas']:
            book[filters_sheet].append(['WOS Thematic Area', wta])
    if 'document_type' in filters:
        book[filters_sheet].append(['Document Type', filters['document_type']])
    if 'document_type_details' in filters:
        for dtd in filters['document_type_details']:
            book[filters_sheet].append(['Document', dtd])
    return gfile_download("[SciELO]Documents", "xlsx", book)

BibliometricsApp/app/v1/controllers/indexController.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template,\
                  session, redirect, url_for,\
                  request, jsonify, make_response,\
                  flash, current_app
from datetime import datetime
from math import log
from app.helper_dicts.COLLECTION_DICTS import COUNTRY_COLLECTIONS,\
                                              NOT_COLLECTIONS,\
                                              COLLECTIONS
from app.helper_dicts.ISO_3166_ALPHA3 import ISO_3166_ALPHA3
from app.helper_dicts.ISO_639_ALPHA2 import ISO_639_ALPHA2
from app.v1.helpers.elasticQueries import elasticQueries
from app.v1.classes.filters import Filters
from app.v1.classes.publicationStats import PublicationStats

import pyexcel as pe
import io
import requests
import os.path
import random
import json

VERSION = "v1"
mod_index = Blueprint('v1_indexController', __name__, url_prefix='/'+VERSION)

#-- ----------------------------------------------------------------

@mod_index.route('/')
def index():
    filters = Filters()
    if request.args.get('lang'):
        filters.lang = request.args.get('lang')
    elif request.form.get('lang'):
        filters.lang = request.form.get('lang')
        
    cache_filename = current_app.config.get("CACHE_FOLDER_PATH")+VERSION+'/data/index.json'
    if not os.path.exists(cache_filename):
        publication = PublicationStats(current_app.config.get("SERVER"), current_app.config.get("PUBLICATIONSTATS"))
        response = publication.data_index()
        by_collection = response["aggregations"]["by_collection"]["buckets"]
        data = []
        for i in by_collection:
          if str(i["key"]) in COUNTRY_COLLECTIONS:       
            alpha3 = COUNTRY_COLLECTIONS[str(i["key"])]
            data.append({
              "country-code": ISO_3166_ALPHA3[alpha3]["code"],
              "country-name": ISO_3166_ALPHA3[alpha3]["fullname"],
              "documents": i["doc_count"],
              "journals": len(i["by_journal"]["buckets"])
            })
        j = { 'data': data }
        with open(cache_filename, 'w') as json_file:
            json.dump(j, json_file, ensure_ascii=True, sort_keys=True, indent=4)
    with open(cache_filename) as data_file:    
        json_data = json.load(data_file)
        data = json_data['data']

    return render_template("v1/index/index.html", filters = filters, data = data).encode( "utf-8" )

#-- ----------------------------------------------------------------

@mod_index.route('/history')
def history():
    filters = Filters()
    return render_template("v1/index/history.html", filters = filters, ISO_3166_ALPHA3 = ISO_3166_ALPHA3,
                            country_collections = COUNTRY_COLLECTIONS, not_collections = NOT_COLLECTIONS,
                            ISO_639_ALPHA2 = ISO_639_ALPHA2)

#-- ----------------------------------------------------------------

@mod_index.route('/user_history')
def user_history():
    filters = Filters()
    return render_template("v1/index/user_history.html", filters = filters, ISO_3166_ALPHA3 = ISO_3166_ALPHA3,
                            country_collections = COUNTRY_COLLECTIONS, not_collections = NOT_COLLECTIONS,
                            ISO_639_ALPHA2 = ISO_639_ALPHA2)

#-- ----------------------------------------------------------------
#Conjunto de métodos para crear el json de filtros avanzados
#-- ----------------------------------------------------------------
@mod_index.route('/gfilters')
def gfilters():
    #Obtenemos información para los filtros
    publication = PublicationStats(current_app.config.get("SERVER"), current_app.config.get("PUBLICATIONSTATS"))
    data = {}
    data['thematicAreas']  = get_subject_areas(publication)
    data['wosThematicAreas']  = get_wos_subject_areas(publication)
    data['collections'] = [ [ c, COLLECTIONS[c][0] ] for c in get_collections(publication) ]
    data['documentTypes'] = get_document_types(publication)
    
    #Languages
    data['languages'] = []
    languages = get_languages(publication)
    for l in languages:
        data['languages'].append([l, ISO_639_ALPHA2[l]['english']] if l in ISO_639_ALPHA2 else [l, l]) 
    
    data['journals'] = get_journals(publication)
    return jsonify(data)

#-- ----------------------------------------------------------------

def get_thematic_areas(publication):
    response = publication.query_3()
    return [ a['key'] for a in response["aggregations"]["by_area"]["buckets"] ]

def get_subject_areas(publication):
    response = publication.query_article_distinct_field("subject_areas")
    return [ t['key'] for t in response["aggregations"]["by_value"]["buckets"] ]

def get_wos_subject_areas(publication):
    response = publication.query_article_distinct_field("wos_subject_areas")
    return [ t['key'] for t in response["aggregations"]["by_value"]["buckets"] ]

def get_collections(publication):
    response = publication.query_article_distinct_field("collection")
    return [ c['key'] for c in response["aggregations"]["by_value"]["buckets"] ]

def get_document_types(publication):
    response = publication.query_article_distinct_field("document_type")
    return [ dt['key'] for dt in response["aggregations"]["by_value"]["buckets"] ]

def get_languages(publication):
    response = publication.query_article_distinct_field("languages")
    return [ l['key'] for l in response["aggregations"]["by_value"]["buckets"] ]

def get_journals(publication):
    response = publication.query_article_distinct_field("journal_title")
    return [ j['key'] for j in response["aggregations"]["by_value"]["buckets"] ]

#-- ----------------------------------------------------------------
#Fin métodos para crear el json de filtros avanzados
#-- ----------------------------------------------------------------

BibliometricsApp/app/templates/v1/partials/filters-index.html
<form id="filters-form" method=post>
  <div id="filters-container">
    <!-- FILTERS PANEL -->
    <div id="filter-panel">
      <input type="hidden" id="filters-form-uhid" name="uhid">
      <input type="hidden" id="filters-form-lang" name="lang" value="{{ session['lang'] }}">
      <input type="hidden" id="filters-form-url" name="url" value="">
      <div class="row margin-0">
        <div class="col s3">
          <div class="input-field">
            <select id="scope-select" name="scope"></select>
            <label>{{ gettext("Scope") }}</label>
          </div>
        </div>
        <div class="col s5">
          <div class="input-field">
            <select id="scope-tabulations-select" name="tabulation"></select>
            <label>{{ gettext("Tabulation") }}</label>
          </div>
        </div>
        <div class="col s3">
          <div class="input-field">
            <select id="scope-tabulation-visualizations-select" name="visualization"></select>
            <label id="vis-label" class="parpadea">{{ gettext("Visualization") }}</label>
          </div>
        </div>
        <div id="fp-btns" class="col s1">
          <button id="visulize-btn" type="submit" class="btn btn-pp scielo-blue waves-effect waves-light tooltipped disabled" data-position="top" disabled="disabled" data-tooltip="{{ gettext('Visualize') }}" onclick="save_to_history('#filters-form');"><i class="fa fa-search" aria-hidden="true"></i></button><br>
        </div>
      </div>
    </div>
  </div>
</form>


<script type="text/javascript">
  $(document).ready(function(){
    $('.tooltipped').tooltip({delay: 50});
  });
</script>

BibliometricsApp/app/templates/v1/partials/filters.html
<form id="filters-form" method=post>
  <div id="filters-container">
    <!-- FILTERS PANEL -->
    <div id="filter-panel">
      <input type="hidden" id="filters-form-uhid" name="uhid">
      <input type="hidden" id="filters-form-lang" name="lang" value="{{ session['lang'] }}">
      <input type="hidden" id="filters-form-url" name="url" value="">
      <div id="filter-panel-row" class="row">
        <div id="current-visualization-info" class="col s2 m3 l3 show-hide-cv" onclick="$('#current-visualization-details').toggle('slow');">
          <div class="col s3 m3 l3">
            <center><label class="show-hide-cv">{{ gettext("Working<br>Process")}}</label></center>
            <center id="user-history-id-container" class="scielo-blue show-hide-cv">
              <span id="user-history-id" class="show-hide-cv"></span>
            </center>           
          </div>
          <div class="col s9 m9 l9 show-hide-cv">
            <span class='scope-tabulation-fe show-hide-cv'></span>
            <span class="caret show-hide-cv">▼</span>
          </div>
        </div>
        <div id="fp-ss" class="col s2 m2 l2">
          <div class="input-field">
            <select id="scope-select" name="scope"></select>
            <label>{{ gettext("Scope") }}</label>
          </div>
        </div>
        <div id="fp-sts" class="col s3 m3 l3">
          <div class="input-field">
            <select id="scope-tabulations-select" name="tabulation"></select>
            <label>{{ gettext("Tabulation") }}</label>
          </div>
        </div>
        <div id="fp-stvs" class="col s2 m2 l2">
          <div class="input-field">
            <select id="scope-tabulation-visualizations-select" name="visualization"></select>
            <label id="vis-label" class="parpadea">{{ gettext("Visualization") }}</label>
          </div>
        </div>
        <div id="fp-btns" class="col s2 m2 l2">
          <center>
            <button id="visulize-btn" type="submit" class="btn btn-pp scielo-blue waves-effect waves-light tooltipped disabled" data-position="top" disabled="disabled" data-tooltip="{{ gettext('Visualize') }}" onclick="save_to_history('#filters-form');"><i class="fa fa-search" aria-hidden="true"></i></button>
            <a id="new-visulize-btn" href='#new-btn-modal' class="btn btn-pp modal-trigger scielo-blue waves-effect waves-light tooltipped" data-position="top" data-tooltip="{{ gettext('New Visualization') }}"><i class="fa fa-plus" aria-hidden="true"></i></a>
          </center>
          <br>
        </div>
      </div>
    </div>
  </div> 
</form>

<script type="text/javascript">
  $(document).ready(function(){
    $('.tooltipped').tooltip({delay: 50});
  });
</script>

BibliometricsApp/app/templates/v1/partials/scope-1-export-options.html
<!-- Dropdown Trigger -->
<a id="export-option-btn" class='dropdown-button scielo-blue-text' href='#' data-activates='export-options-dropdown' title="Export Options"><i class="fa fa-bars" aria-hidden="true" style="font-size: 1.3em"></i> </a>
<!-- Dropdown Structure -->
<ul id='export-options-dropdown' class='dropdown-content'>
  <li class="print-export-option">
		<a onclick="printSVG('#visualization-area')">Print</a>
	</li>
  <li class="image-export-option">
  	<a id="eo-png" onclick="export_visualization('#world-map svg', 'png');">Export as PNG image</a>
  </li>
  <li class="image-export-option">
  	<a id="eo-jpeg" onclick="export_visualization('#world-map svg', 'jpeg');">Export as JPEG image</a>
  </li>
  <li class="image-export-option">
  	<a id="eo-svg" onclick="export_visualization('#world-map svg', 'svg');">Export as SVG vector image</a>
  </li>
  <li class="image-export-option">
  	<a id="eo-ppt" onclick="export_visualization('#world-map svg', 'pptx');">Export as PPT Slide</a>
  </li>
  <li class="xls-export-option">
    <form id="export-data-xls-form" action="{{ url_for('v1_exporterController.export') }}" method=post>
      {% if filters.tabulation == "1" %}
      	<input type="hidden" name="header1" value="Collection">
      {% elif filters.tabulation == "2" %}
      	<input type="hidden" name="header1" value="Thematic Area">
      {% elif filters.tabulation == "3" %}
      	<input type="hidden" name="header1" value="Language">
      {% elif filters.tabulation == "4" %}
      	<input type="hidden" name="header1" value="Country of Author's Affiliation">
      {% elif filters.tabulation == "5" %}
      	<input type="hidden" name="header1" value="Journal">
      {% else %}
      	<input type="hidden" name="header1" value="Header">
      {% endif %}
      <input type="hidden" name="header2" value="Year">
      <input type="hidden" name="filters" value="{{ filters.serialize }}">
      <input type="hidden" name="data" value="{{ data_table["by_year"] }}">
    </form>
    <a onclick="$('#export-data-xls-form').submit();">Export as XLS file</a>
  </li>
  <li class="pdf-export-option">
  	<a id="eo-pdf" onclick="export_visualization('#world-map svg', 'pdf');">Export as PDF file</a>
  </li>
</ul>

<a id="export-svg-as-image" style="display: none;"></a>
<canvas id="exporter-canvas" style="display: none;"></canvas>

BibliometricsApp/app/templates/v1/partials/scope-2-export-options.html
<!-- Dropdown Trigger -->
<a id="export-option-btn" class='dropdown-button scielo-blue-text' href='#' data-activates='export-options-dropdown' title="Export Options"><i class="fa fa-bars" aria-hidden="true" style="font-size: 1.3em"></i> </a>
<!-- Dropdown Structure -->
<ul id='export-options-dropdown' class='dropdown-content'>
  <li class="print-export-option">
    <a onclick="printSVG('#visualization-area')">Print</a>
  </li>
  <li class="image-export-option">
    <a id="eo-png" onclick="export_visualization('#world-map svg', 'png');">Export as PNG image</a>
  </li>
  <li class="image-export-option">
    <a id="eo-jpeg" onclick="export_visualization('#world-map svg', 'jpeg');">Export as JPEG image</a>
  </li>
  <li class="image-export-option">
    <a id="eo-svg" onclick="export_visualization('#world-map svg', 'svg');">Export as SVG vector image</a>
  </li>
  <li class="image-export-option">
    <a id="eo-ppt" onclick="export_visualization('#world-map svg', 'pptx');">Export as PPT Slide</a>
  </li>
  <li class="xls-export-option">
    <form id="export-data-xls-form" action="{{ url_for('v1_exporterController.export_journal') }}" method=post>
      {% if filters.tabulation == "1" %}
        <input type="hidden" name="header1" value="Collection">
      {% elif filters.tabulation == "2" %}
        <input type="hidden" name="header1" value="Thematic Area">
      {% elif filters.tabulation == "3" %}
        <input type="hidden" name="header1" value="Language">
      {% else %}
        <input type="hidden" name="header1" value="Header">
      {% endif %}
      <input type="hidden" name="header2" value="Year">
      <input type="hidden" name="filters" value="{{ filters.serialize }}">
      <input type="hidden" name="data" value="{{ data_table["by_year"] }}">
    </form>
    <a onclick="$('#export-data-xls-form').submit();">Export as XLS file</a>
  </li>
  <li class="pdf-export-option">
    <a id="eo-pdf" onclick="export_visualization('#world-map svg', 'pdf');">Export as PDF file</a>
  </li>
</ul>

<a id="export-svg-as-image" style="display: none;"></a>
<canvas id="exporter-canvas" style="display: none;"></canvas>

BibliometricsApp/app/templates/v1/partials/scope-7-export-options.html
<!-- Dropdown Trigger -->
<a id="export-option-btn" class='dropdown-button scielo-blue-text' href='#' data-activates='export-options-dropdown' title="Export Options"><i class="fa fa-bars" aria-hidden="true" style="font-size: 1.3em"></i></a>
<!-- Dropdown Structure -->
<ul id='export-options-dropdown' class='dropdown-content'>
  <li class="print-export-option">
		<a onclick="printSVG('#visualization-area')">Print</a>
	</li>
  <li class="image-export-option hide-for-map">
  	<a id="eo-png" onclick="export_visualization('#circular-layout svg', 'png');">Export as PNG image</a>
  </li>
  <li class="image-export-option hide-for-map">
  	<a id="eo-jpeg" onclick="export_visualization('#circular-layout svg', 'jpeg');">Export as JPEG image</a>
  </li>
  <li class="image-export-option">
  	<a id="eo-svg" onclick="export_visualization('#circular-layout svg', 'svg');">Export as SVG vector image</a>
  </li>
  <li class="image-export-option hide-for-map">
  	<a id="eo-ppt" onclick="export_visualization('#circular-layout svg', 'pptx');">Export as PPT Slide</a>
  </li>
  <li class="pdf-export-option hide-for-map">
  	<a id="eo-pdf" onclick="export_visualization('#circular-layout svg', 'pdf');">Export as PDF file</a>
  </li>
</ul>
<canvas id="exporter-canvas" style="display: none;"></canvas>

BibliometricsApp/app/templates/v1/partials/social_networks.html
<div style="display: inline; margin: 0px 40px;">
	<a class="share-class scielo-blue-text" href="https://www.facebook.com/sharer/sharer.php?u={{ url }}" title="Share on Facebook">
		<i class="fa fa-facebook-official" aria-hidden="true" style="font-size: 1.3em"></i>
	</a>
	<a class="share-class scielo-blue-text" href="https://plus.google.com/share?url={{ url }}" title="Share on Google+">
		<i class="fa fa-google-plus-square" aria-hidden="true" style="font-size: 1.3em"></i>
	</a>
	<a class="share-class scielo-blue-text" href="https://twitter.com/share?url={{ url }}&hashtags=[SciELO]" title="Share on Twitter">
		<i class="fa fa-twitter-square" aria-hidden="true" style="font-size: 1.3em"></i>
	</a>
	<a class="share-class scielo-blue-text" href="http://reddit.com/submit?url={{ url }}" title="Share on Reddit">
		<i class="fa fa-reddit-square" aria-hidden="true" style="font-size: 1.3em"></i>
	</a>
	<a class="share-class scielo-blue-text" href="http://www.linkedin.com/shareArticle?url={{ url }}" title="Share on LinkedIn">
		<i class="fa fa-linkedin-square" aria-hidden="true" style="font-size: 1.3em"></i>
	</a>
	<a class="share-class scielo-blue-text" href="https://pinterest.com/pin/create/bookmarklet/?url={{ url }}" title="Share on Printerest">
		<i class="fa fa-pinterest-square" aria-hidden="true" style="font-size: 1.3em"></i>
	</a>
	<a class="share-class scielo-blue-text" href="http://www.tumblr.com/share/link?url={{ url }}" title="Share on Tumblr">
		<i class="fa fa-tumblr-square" aria-hidden="true" style="font-size: 1.3em"></i>
	</a>
	<a class="scielo-blue-text" href="mailto:?subject=SciELO Visualization&amp;body=Check out this {{url}}."
	   title="Share by Email">
		<i class="fa fa-envelope" aria-hidden="true" style="font-size: 1.3em"></i>
	</a>	
</div>

{% if filters.scope == "1" %}
<div style="display: inline;">
	<a id="animate-btn" class="scielo-blue-text" title="Animate Visualization">
	  <i class="fa fa-play-circle" aria-hidden="true" onclick="change_visualization('{{ filters.visualization }}', true);" style="font-size: 1.3em"></i>
	</a>
</div>
{% endif %}

<script type="text/javascript">
	$(document).ready(function() {
	    $('.share-class').click(function(e) {
	        e.preventDefault();
	        window.open($(this).attr('href'), 'ShareWindow', 'height=450, width=550, top=' + ($(window).height() / 2 - 275) + ', left=' + ($(window).width() / 2 - 225) + ', toolbar=0, location=0, menubar=0, directories=0, scrollbars=0');
	        return false;
	    });
	});
</script>